/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aritmatika;

/**
 *
 * @author diniristanti
 */
public class mat extends javax.swing.JFrame {
    String jjenis = "";
    int jjumlah;

    /**
     * Creates new form mat
     */
    public mat() {
        initComponents();
        jjenis = null;
        panel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jbil = new javax.swing.JComboBox<>();
        label1 = new javax.swing.JLabel();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JTextField();
        label3 = new javax.swing.JLabel();
        bil4 = new javax.swing.JTextField();
        label4 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        berapa = new javax.swing.JTextArea();
        ket = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PROGRAM ARITMATIKA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 180, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 54, 100, 20);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih salah satu--", "penjumlahan", "pengurangan", "pembagian", "perkalian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(170, 50, 250, 30);

        panel.setBackground(new java.awt.Color(204, 204, 204));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        panel.setForeground(new java.awt.Color(153, 153, 153));
        panel.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Jumlah Bilangan");
        panel.add(jLabel3);
        jLabel3.setBounds(30, 70, 100, 20);

        jbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "2", "3", "4" }));
        jbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbilActionPerformed(evt);
            }
        });
        panel.add(jbil);
        jbil.setBounds(160, 60, 190, 30);

        label1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label1.setText("Bilangan 1");
        panel.add(label1);
        label1.setBounds(30, 110, 60, 20);

        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        panel.add(bil1);
        bil1.setBounds(160, 100, 190, 30);
        panel.add(bil2);
        bil2.setBounds(160, 140, 190, 30);

        label2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label2.setText("Bilangan 2");
        panel.add(label2);
        label2.setBounds(30, 150, 60, 20);
        panel.add(bil3);
        bil3.setBounds(160, 180, 190, 30);

        label3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label3.setText("Bilangan 3");
        panel.add(label3);
        label3.setBounds(30, 190, 60, 20);
        panel.add(bil4);
        bil4.setBounds(160, 220, 190, 30);

        label4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label4.setText("Bilangan 4");
        panel.add(label4);
        label4.setBounds(30, 230, 60, 20);

        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        panel.add(hitung);
        hitung.setBounds(180, 260, 140, 30);

        berapa.setColumns(20);
        berapa.setRows(5);
        jScrollPane3.setViewportView(berapa);

        panel.add(jScrollPane3);
        jScrollPane3.setBounds(80, 310, 250, 70);

        ket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panel.add(ket);
        ket.setBounds(130, 20, 170, 30);

        getContentPane().add(panel);
        panel.setBounds(20, 90, 420, 390);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 460, 490);

        setBounds(0, 0, 476, 531);
    }// </editor-fold>//GEN-END:initComponents

    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil1ActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
         setJenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void jbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbilActionPerformed
        // TODO add your handling code here:
        getJumlah();
        
    }//GEN-LAST:event_jbilActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        Double hasil = 0.0;
        Double b1,b2,b3,b4;
        b1 = Double.parseDouble(bil1.getText().toString());
        b2 = Double.parseDouble(bil2.getText().toString());
        b3 = Double.parseDouble(bil3.getText().toString());
        b4 = Double.parseDouble(bil4.getText().toString());
        
        if (jjenis.equals("penjumlahan")) {
            if(jjumlah == 2){
                hasil = b1 + b2;
                berapa.setText(""+b1 + " + "+b2+" = "+hasil);
            }
            if(jjumlah == 3){
                hasil = b1 + b2 + b3;
                berapa.setText(""+b1 + " + "+b2+ " + "+b3+" = "+hasil);
            }
            if(jjumlah == 4){
                hasil = b1 + b2 + b3 + b4;
                berapa.setText(""+b1 + " + "+b2+ " + "+b3+" + " + b4 +" = "+hasil);
            }
        } else
            if (jjenis.equals("pengurangan")) {
            if(jjumlah == 2){
                hasil = b1 - b2;
                berapa.setText(""+b1 + " - "+b2+" = "+hasil);
            }
            if(jjumlah == 3){
                hasil = b1 - b2 - b3;
                berapa.setText(""+b1 + " - "+b2+ " - "+b3+" = "+hasil);
            }
            if(jjumlah == 4){
                hasil = b1 - b2 - b3 - b4;
                berapa.setText(""+b1 + " - "+b2+ " - "+b3+" - " + b4 +" = "+hasil);
            }
        } else
        if (jjenis.equals("perkalian")) {
            if(jjumlah == 2){
                hasil = b1 * b2;
                berapa.setText(""+b1 + " x "+b2+" = "+hasil);
            }
            if(jjumlah == 3){
                hasil = b1 * b2 * b3;
                berapa.setText(""+b1 + " x "+b2+ " x "+b3+" = "+hasil);
            }
            if(jjumlah == 4){
                hasil = b1 * b2 * b3 * b4;
                berapa.setText(""+b1 + " x "+b2+ " x "+b3+" x " + b4 +" = "+hasil);
            }
        }
        if (jjenis.equals("pembagian")) {
            if(jjumlah == 2){
                hasil = b1 / b2;
                berapa.setText(""+b1 + " : "+b2+" = "+hasil);
            }
            if(jjumlah == 3){
                hasil = b1 / b2 / b3;
                berapa.setText(""+b1 + " : "+b2+ " : "+b3+" = "+hasil);
            }
            if(jjumlah == 4){
                hasil = b1 / b2 / b3 / b4;
                berapa.setText(""+b1 + " : "+b2+ " : "+b3+" : " + b4 +" = "+hasil);
            }
        }
        
    }//GEN-LAST:event_hitungActionPerformed
    private void setJenis() {
        
        if(jenis.getSelectedItem().equals("penjumlahan")){
            jjenis = "penjumlahan";
            ket.setText("penjumlahan");
            panel.setVisible(true);
            jbil.setEnabled(true);
            
         }else
         if(jenis.getSelectedItem().equals("pengurangan")){
            jjenis = "pengurangan";
            ket.setText("pengurangan");
            panel.setVisible(true);
            jbil.setEnabled(true);
         }else
         if(jenis.getSelectedItem().equals("pembagian")){
            jjenis = "pembagian";
            ket.setText("pembagian");
            panel.setVisible(true);
            jbil.setEnabled(true);
         }else
         if(jenis.getSelectedItem().equals("perkalian")){
            jjenis = "perkalian";
            ket.setText("perkalian");
            panel.setVisible(true);
            jbil.setEnabled(true);
         }else
         {
             jjenis = null;
             panel.setVisible(false);
         }
             
    }
    private void getJumlah() {
        if(jbil.getSelectedItem().equals("--")){
            bil1.setVisible(false);
            bil2.setVisible(false);
            label1.setVisible(false);
            label2.setVisible(false);
            bil3.setVisible(false);
            bil4.setVisible(false);
            label3.setVisible(false);
            label4.setVisible(false);
            jjumlah = 0;
        } else
        if(jbil.getSelectedItem().equals("2")){
            bil3.setVisible(false);
            bil4.setVisible(false);
            label3.setVisible(false);
            label4.setVisible(false);
            jjumlah = 2;
        } else
        if(jbil.getSelectedItem().equals("3")){
            bil3.setVisible(true);
            bil4.setVisible(false);
            label3.setVisible(true);
            label4.setVisible(false);
            jjumlah = 3;
        } else
        if(jbil.getSelectedItem().equals("4")){
            bil3.setVisible(true);
            bil4.setVisible(true);
            label3.setVisible(true);
            label4.setVisible(true);
            jjumlah = 4;
        } 
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mat().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea berapa;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JComboBox<String> jbil;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

    

    
}
